# Generated by Django 5.1.3 on 2024-11-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Основной текст стаьи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления поста')),
            ],
        ),
    ]
